apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql-{{ .Values.environment }}
  namespace: {{ .Values.namespace }}
  labels:
    app: mysql
    environment: {{ .Values.environment }}
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
  - port: {{ .Values.mysql.service.port }}
    targetPort: mysql
    protocol: TCP
    name: mysql
  selector:
    app: mysql
    environment: {{ .Values.environment }}
