apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.env.MYSQL_ROOT_PASSWORD | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.env.MYSQL_DATABASE | quote }}
  MYSQL_USER: {{ .Values.mysql.env.MYSQL_USER | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.env.MYSQL_PASSWORD | quote }}
