apiVersion: v1
kind: Service
metadata:
  name: wordpress-{{ .Values.environment }}
  namespace: {{ .Values.namespace }}
  labels:
    app: wordpress
    environment: {{ .Values.environment }}
spec:
  type: {{ .Values.wordpress.service.type }}
  ports:
  - port: {{ .Values.wordpress.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: wordpress
    environment: {{ .Values.environment }}
